### PR TITLE
add required param "options" to pino-pretty in the transport example

### PR DESCRIPTION
**Pull request by AskAlice**

### CODE REVIEW

**Comment by jsumners** [comment]
Can you help me understand why it's required? If I'm not mistaken, the provided example is the default.

**Comment by AskAlice** [comment]
> Can you help me understand why it's required? If I'm not mistaken, the provided example is the default.

Typescript error

**Comment by jsumners** [comment]
Can you provide some more context? Is this something that needs to be fixed with code instead of documentation? Simply stating "Typescript error" is not giving me anything to go on.

**Comment by mcollina** [comment]
Closing for no activity

**Pull request closed without merging**
