### PR TITLE
Do not cast to string Error#stack.

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/pinojs/pino-pretty/issues/16.

@jsumners @davidmarkclements what do you think?

### CODE REVIEW

**Comment by davidmarkclements** [comment]
yes I agree - but this is now a breaking change, so should be in v5 but not v4

**Comment by davidmarkclements** [comment]
We also need to discuss one case:

If I  `delete err.stack` then "stack" should not show.

However if I assign: `err.stack = undefined`, then some make the argument that they'd like to see, in some way, that it's been set to `undefined`. Which is how we got here.

So, should we set stack to an empty string when the `stack` is present but the value is `undefined`?

**Comment by mcollina** [comment]
> yes I agree - but this is now a breaking change, so should be in v5 but not v4

I don't think so. We landed a botched commit that we shouldn't. Let's restore proper behavior.

> However if I assign: err.stack = undefined, then some make the argument that they'd like to see, in some way, that it's been set to undefined. Which is how we got here.

No, you do not want to see it. Mainly because:

```js
pino.info({ hello: undefined })
```

Will not show the `'hello'` property. `undefined` is invisible in JSON, and it is equal to `delete`.

**Comment by mcollina** [comment]
I do not know how to run that, and there are no instructions. However it does fix the pino-pretty test, so I think we are good to go.

**Comment by davidmarkclements** [comment]
To run just go to travis and restart build for master - prior to release. We don't have a way to run for pr's atm

**Pull request merged**
