### PR TITLE
add caller printing debug feature, closes #191

### LINKED ISSUE #191: print caller name for debugging purpose
hi,

it would be nice to have the ability to print the caller function name of the logging functions in order to easily remove useless log statements when you don't know where they are located in big projects.
obvioulsy this feature will kill the awesome performance of pino so it **MUST** be disabled by default.

i will open a PR with the proposed feature in order to discuss about it.

### PR DESCRIPTION
**Pull request by phra**
see #191 for more infos.

### CODE REVIEW

**Comment by jsumners** [comment]
Can we see some sample output? How about some benchmarks with it disabled versus the master branch?

**Comment by phra** [comment]
i've created a live example of the feature at https://github.com/phra/pino-caller-usage
the performance are the same when the options is disabled thanks to v8 DCE because this [line](https://github.com/phra/pino/blob/features/caller/pino.js#L197) will become `if (false)`.

an output example:
```
╭─phra at debian in /home/phra/git/pino-usage (master ✔)
╰─λ node index.js                                      0 < 21:35:20
{"pid":41795,"hostname":"debian","level":50,"time":1487281257376,"msg":"lol","caller":"Object.<anonymous>()@/home/phra/git/pino-usage/module.js:3:6","v":1}
{"pid":41795,"hostname":"debian","level":30,"time":1487281257380,"msg":"hello world","caller":"Object.<anonymous>()@/home/phra/git/pino-usage/index.js:6:6","v":1}
{"pid":41795,"hostname":"debian","level":50,"time":1487281257380,"msg":"hello world","caller":"Object.<anonymous>()@/home/phra/git/pino-usage/index.js:7:6","v":1}
```
as you can see the logger will display the filename and also the line number where the invocation is located.

**Comment by jsumners** [comment]
I'd still like to see the output of at least `npm run bench-basic` from both branches.

@mcollina @davidmarkclements what are your thoughts on this? If it's accepted, would this necessitate an increase to the log version number?

**Comment by phra** [comment]
see attachments.
[master.perf.txt](https://github.com/pinojs/pino/files/781672/master.perf.txt)
[caller.perf.txt](https://github.com/pinojs/pino/files/781673/caller.perf.txt)

**Comment by davidmarkclements** [comment]
yah it's a nice idea - but I think this should be a plugin - not in core

**Comment by phra** [comment]
@davidmarkclements any ideas how to implement this as a plugin?

**Comment by jsumners** [comment]
I think the simplest solution is just: `log.debug('functionName: this is a log message')`

**Comment by davidmarkclements** [comment]
One potentially elegant way would be to create a child logger with an object that has a caller property, but the property is actually a getter (e.g. defined with Object.defineProperties) - create an error and get the stack in the getter function for caller, and return the relevant call site from the getter. This would result in the same output.

The plugin interface could either be a function that takes a pino instance and returns child logger

**Comment by davidmarkclements** [comment]
using getter for call stack doesn't work - but here you go this will work, feel free to make into a module with tests etc. and we can look at bringing to pino org if you like

```js
function traceCall (pinoInstance) {
  var facade = Object.create(pinoInstance)
  Object.keys(pinoInstance.levels.values)
    .forEach(function (level) {
      facade[level] = makeCallSiteGetter(level)
    })
  function makeCallSiteGetter (level) {
    return function getCallSite () {
      var child = pinoInstance.child({
        caller: Error().stack.split('\n')[3].trim().replace('at ', '')
      })
      return child[level].apply(child, arguments)
    }
  }
  return facade
}
```

example usage
```js
var pino = traceCall(require('./')())
function x() {
  pino.info('hi')
}

x()
```

output: 

```sh
{"pid":25503,"hostname":"NY5-Consult01","level":30,"time":1487342685938,"msg":"hi","caller":"x (/Users/dclements/pino/x.js:20:8)","v":1}
```

**Comment by phra** [comment]
@davidmarkclements thanks, i will do it when i have spare time! 😺

**Comment by davidmarkclements** [comment]
awesome - closing PR and issue - thank @phra :bowtie:

**Pull request closed without merging**
