### PR TITLE
std serializers api typo + deprecation unit tests

### PR DESCRIPTION
**Pull request by davidmarkclements**
this is a no brainer to fix, 

however: I'm assuming this is a patch release not a major, because even though we're technically changing the API - we should consider the current API broken

I doubt anyone is relying on the typo, we would have had a PR by now... surely

### CODE REVIEW

**Comment by davidmarkclements** [comment]
can we get another round, I've introduced an approach to deprecating with tests

**Comment by davidmarkclements** [comment]
(this also increases coverage, tests the slowtime deprecation)

**Comment by davidmarkclements** [comment]
failing in v4 because `emitWarning` isn't on `process`. 

That means technically we've been failing on v4 since slowtime was deprecated.

**Comment by jsumners** [comment]
What do you guys want to do about v4? I would be okay with dropping support early since there is only a month of LTS left on it. But it's also possible to detect if `emitWarning` is unavailable and simply use `emit`.

**Comment by davidmarkclements** [comment]
but we'd also have to do `process.on('warning', console.error)` 

we could just switch to using `util.deprecate` - which behaves differently in v4

it will make testing trickier but thats the least leaky approach in `pino.js`

**Comment by jsumners** [comment]
Again, I'm okay with whichever route.

**Comment by davidmarkclements** [comment]
I'd prefer to just drop support for v4

realistically, anyone on v4 will still be able to use current pino for at least the next month,
we just stop testing against it early

@mcollina what do you think?

**Comment by davidmarkclements** [comment]
Although if we drop support for v4 it's a major release - and none of these current deprecation issues matter

**Comment by mcollina** [comment]
https://nodejs.org/api/util.html#util_util_deprecate_function_string was added in Node 0.8. It's pretty safe to use.

**Comment by davidmarkclements** [comment]
but much harder to test across versions because it behaves differently

However, it's probably the right approach, otherwise we have to start talking a major release

**Comment by davidmarkclements** [comment]
ok, switched to util.deprecate tests are passing in every version

**Pull request merged**
