### PR TITLE
Replace fast-safe-stringify with json-stringify-safe

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/pinojs/pino/issues/1062

### CODE REVIEW

**Review by jsumners — APPROVED** [review]

**Comment by mcollina** [comment]
Should we ship this in v7 or v6?

**Comment by climba03003** [comment]
Will it be the problem https://github.com/BridgeAR/safe-stable-stringify/issues/17 ?
Currently, `level` will place first for logging and it is easier to trace. With this update, it may becomes `hostname` or something unpredictable because of custom `bindings`.

**Comment by jsumners** [comment]
> Should we ship this in v7 or v6?

7

**Comment by mcollina** [comment]
> Will it be the problem [BridgeAR/safe-stable-stringify#17](https://github.com/BridgeAR/safe-stable-stringify/issues/17) ?
> Currently, `level` will place first for logging and it is easier to trace. With this update, it may becomes `hostname` or something unpredictable because of custom `bindings` when `JSON.stringify` failed.

I replaced it with json-stringify-safe instead. It's an old module which is incredibly stable and trusted. The algorithm is quite simple, we could even think of vendoring some iteration of that code.

**Review by jsumners — APPROVED** [review]

**Comment by mcollina** [comment]
I moved this to `next` in https://github.com/pinojs/pino/pull/1066. It was simpler to redo as there were a bit of conflicts to rebase.

**Pull request closed without merging**
