### PR TITLE
Fix: TypeScript: Make TransportOptions optional

### PR DESCRIPTION
**Pull request by glensc**
Options is not optional currently:
- https://github.com/pinojs/pino/blob/5d8eb719761003bce52d12ccc9e0a5b69ef9e185/pino.d.ts#L227

### CODE REVIEW

**Comment by mcollina** [comment]
Could you fix the TS definitions instead? That's not mandatory.

**Comment by glensc** [comment]
Dropped f3b439c8f19ad657ebce0b658416d2e2c6e501b6, added 931e06d.

**Comment by glensc** [comment]
CI failing is not related to the changes. Retry shows random jobs failing.

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add a test for the type? We use tsd.

**Comment by mcollina** [comment]
Closing for no activity

**Pull request closed without merging**
