### PR TITLE
replace extreme destination with async destination

### PR DESCRIPTION
**Pull request by mksmtn**
`extreme` destination does not exist on `pino` anymore

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I would just drop all that v4/v5 section. It's probably  for the best, those are really old!

**Comment by mksmtn** [comment]
You mean like that?

**Comment by mcollina** [comment]
You'd need to delete it from https://github.com/pinojs/pino/blob/master/docsify/sidebar.md and the README. Thanks!

**Comment by mksmtn** [comment]
Oh, didn't read the notice "Sorry, forked repositories are not currently searchable." and just thought that nothing is found for "legacy" query. Fixed

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]

**Pull request merged**
