### PR TITLE
add pino-pg transport

### PR DESCRIPTION
**Pull request by Xstoudi**

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind to add a unit test for your module?

**Comment by Xstoudi** [comment]
Sure, it's planned for 14th of March.
I'll leave a comment here when it's done.

**Comment by Xstoudi** [comment]
Sorry for the wait, I pushed test and changed the way the transports work. Check it out and let met know if you thing more changes are needed.

**Comment by Xstoudi** [comment]
I think this one is mergeable now that the issue is solved :)

**Pull request merged**
