### PR TITLE
chore: bump serializer library, for https://github.com/pinojs/pino-std…

### PR DESCRIPTION
**Pull request by Mechanicalkeyboard**
see https://github.com/pinojs/pino-std-serializers/issues/88

### CODE REVIEW

**Comment by jsumners** [comment]
This would incur a major bump for Pino. We will do that at some point, but I'm not sure we are ready for it yet. You can use the newer version of `pino-std-serializers` by providing them as serializers when creating your Pino instance -- https://getpino.io/#/docs/api?id=serializers-object

**Comment by voxpelli** [comment]
I would have hoped this would get part of Fastify v4 as a bump in Pino major would have to wait for a Fastify major to be included there and that will I guess take a while before that happens

**Comment by mcollina** [comment]
CI is failing, could you update it?

@voxpelli I cannot delay Fastify v4 further to do another pino major bump :(. We'll likely do a Fastify v5 / pino v8 combo once we are ready.

**Comment by voxpelli** [comment]
@mcollina I totally understand, I should have caught this earlier if I wanted to push it :)

On a sidenote: Why didn't Dependabot suggest this update?

**Comment by kibertoad** [comment]
@mcollina How much work would bump entail? I can contribute some effort if that helps

**Comment by mcollina** [comment]
> @mcollina How much work would bump entail? I can contribute some effort if that helps

Check out https://github.com/pinojs/pino/milestone/4. The most important change that need to be finished is https://github.com/pinojs/pino/pull/1249

**Comment by kibertoad** [comment]
@mcollina #1249 only needs conflicts resolved and CI passing, right? Will attempt that tonight.

**Comment by kibertoad** [comment]
@voxpelli Meanwhile, will you be able to fix this PR?

**Comment by voxpelli** [comment]
@kibertoad I can try, but since it’s not mine and I’m not a maintainer I can only open a new one that replaces this one

**Comment by kibertoad** [comment]
@voxpelli that also works

**Comment by kibertoad** [comment]
@voxpelli fastify v4 lands next Tuesday, so we need pino 8 this week. is it feasible to create a new PR by EOD tomorrow?

**Comment by mcollina** [comment]
Superseded by https://github.com/pinojs/pino/pull/1449

**Pull request closed without merging**
