### PR TITLE
Update transports.md

### PR DESCRIPTION
**Pull request by bloodcarter**
Update to reflect new functionality: support for AWS Elasticsearch for pino-elasticsearch

### CODE REVIEW

**Comment by jsumners** [comment]
Would you mind correcting "Check that you defined `network.host in` your ..." to "Check that your defined `network.host` in your ..." at the same time?

**Comment by bloodcarter** [comment]
What do you mean? It looks OK now.

**Comment by jsumners** [comment]
It's not an error in your change. It's a typo just prior to the text of your change. I'm just asking you'd be willing to make the correction at the same time.

**Comment by bloodcarter** [comment]
@jsumners I got it, but I cannot see the typo in the master.

**Comment by jsumners** [comment]
@bloodcarter never mind. I was misreading the text.

**Pull request merged**
