### PR TITLE
Created a package-lock.json file

### PR DESCRIPTION
**Pull request by mcollina**
As introduced by NPM@5.

Some more details on this are available: https://github.com/npm/npm/pull/16441

### CODE REVIEW

**Comment by jsumners** [comment]
I don't understand the point of this file. That's what the package.json is for, right?

**Comment by mcollina** [comment]
It will be created by npm@5 everywhere, it's the same as yarn.lock, but compatible with the NPM ecosystem.
On the good side, it adds a level of checks on the security of our modules with committed shas.

I'm fine _not_ adding it, but then we will `.gitignore` it.

**Comment by davidmarkclements** [comment]
From the issue, I understand that it's similar to npm-shrinkwrap with a main difference being npm-shrinkwrap get's published to npm, whereas package-lock.json does not

Since we never saw fit to use npm-shrinkwrap, not sure of the benefits of package-lock.json

On a significantly sized application with lots of deps, it could be beneficial - but is it going to just add unnecessary maintenance overhead here?

**Comment by jsumners** [comment]
I don't agree with NPM 5's automatic addition of this file nor its automatic saving of dependencies. Thus, I don't agree with adding this file to the project.

**Comment by mcollina** [comment]
Fantastic. I'll add it to `.gitignore` then.

**Pull request closed without merging**
