### PR TITLE
Add profiling scripts

### PR DESCRIPTION
**Pull request by jsumners**
The goal of this PR is to add a few profiling scripts that exercise the same things as the benchmark scripts. I'm submitting my initial implementation of the basic profile to get your feedback. I don't think this is something that can be automated, but I do think it would be useful when things are majorly changed.

As an example:

I'm not sure when those crept in, if they were always present, or what. But I do know we should look into why they are showing up.

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Good shout @jsumners 

Maybe it can be automated 

@mcollina what if we break out the 0x part of autocannon-ci 
into 0x-ci and used it here?

**Comment by davidmarkclements** [comment]
Oh wait you're doing it in a server context - I think that should 
be done for pino-http but not pino - why add the extra stacks?

**Comment by jsumners** [comment]
I started with several `for` loops but it was too fast (😉) so 0x couldn't trace anything. Putting the for loops in a `setTimeout(500)` worked, but it was a de-opt of its own. So I tried this approach. But that's why I started the PR with so little finished -- to get your help figuring out a good approach.

**Comment by davidmarkclements** [comment]
Oh interesting - same story for setImmediate?

**Comment by mcollina** [comment]
@jsumners I think we can use https://github.com/mcollina/autocannon-ci, if our goal is to generate flamegraphs for HTTP requests.

**Comment by davidmarkclements** [comment]
yah I think that could (and should) be a goal for pino-http

the goal here (as I understand it) is purely to profile pino core - it's just the best way to do that so far is to wrap it in an http server

**Comment by jsumners** [comment]
@davidmarkclements `setImmediate` had the same problem as the basic for loops version -- it completes too quickly for 0x to do anything. FYI, this version of the profile script is also not optimized. But I don't really care about the profile script itself being optimized, so I can easily rewrite it back to using a `setTimeout`.

The goal is to give us a way to, at least manually, verify that core remains as optimized as we can make it.

**Comment by jsumners** [comment]
`node --prof --trace-opt --trace-deopt profile/basic-alt.profile.js 1> trace.out`

[trace.out.txt](https://github.com/pinojs/pino/files/861744/trace.out.txt)
[isolate-0x103000000-v8.processed.log.txt](https://github.com/pinojs/pino/files/861743/isolate-0x103000000-v8.processed.log.txt)

**Comment by jsumners** [comment]
So there are a couple of questions:

1. is this worth the time?
2. which style should be used? The `alt` script I added this morning needed as many iterations as I gave it (5 total) to even register a flamegraph at all.

**Comment by mcollina** [comment]
I don't know if it's worth the time.
I prefer the `alt` version.

**Comment by davidmarkclements** [comment]
Wait. It may be because 0x has a default delay of 300ms to skip module loading stacks and allow for perf and dtrace init 

Trying setting 0x duration to 0

**Comment by jsumners** [comment]
@davidmarkclements `-d 0` allows `basic-alt.profile.js` to act like it is generating data for 0x when the iterations are unwrapped from the `setTimeout`. However, it does not actually generate a flamegraph.

I think I'm going to agree with @mcollina, and say this endeavor is not worth the effort. I think that as long as our benchmarks stay consistent (or even decrease) we are in good shape no matter what optimizations are being done, or not, by V8. So I'm going to close this PR. I'll leave the branch in case we decide otherwise later.

**Pull request closed without merging**
