### PR TITLE
chore(docs): add links to gcp logging formatter

### PR DESCRIPTION
**Pull request by nielm**
Update documentation to include links to [`@google-cloud/pino-logging-gcp-config`](https://www.npmjs.com/package/@google-cloud/pino-logging-gcp-config)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Screenshot 2024-11-18 at 17 45 11

^ This URL is wrong. Could you fix it?

**Review by jsumners — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you resolve the conflicts?

**Comment by nielm** [comment]
Conflict resolved - as they are not sorted by name, this is first in the list /shrug

**Review by jsumners — APPROVED** [review]

**Pull request merged**
