### PR TITLE
Fix browser serializers

### PR DESCRIPTION
**Pull request by jsumners**
Resolves issue #1690

### CODE REVIEW

**Comment by rluvaton** [comment]
you beat me to it 😉

**Comment by jsumners** [comment]
> you beat me to it 😉

Unfortunately, some tests are failing in ways that I cannot reproduce locally.

**Comment by jsumners** [comment]
@mcollina https://github.com/pinojs/pino/actions/runs/4668327008/jobs/8266121575#step:5:36 is consistently timing out. It's something in the transports system. Are you able to take a look?

**Comment by mcollina** [comment]
Possibly in the next few weeks. Things are a bit hectic at the moment and I'm deeply behind my OSS todo.

**Pull request closed without merging**
