### PR TITLE
Added package pino-express

### PR DESCRIPTION
**Pull request by benrei**
Added package pino-express to ecosystem.md#community section

### CODE REVIEW

**Comment by davidmarkclements** [comment]
hey @benrei does this offer anything over `express-pino-logger`?

**Comment by benrei** [comment]
Looks like the only difference is that you can customize log output.

**Comment by davidmarkclements** [comment]
We recommend output customisation is performed with transports

**Comment by benrei** [comment]
I see, sounds like a better solution for most cases.

**Comment by benrei** [comment]
I had another look at `express-pino-logger`. Looks like it doesn't have the feature to check for duration time of a request. I think the `pino-express` could be a nice option for smaller projects with a bit more flexibility, than the minimal and fast `express-pino-logger`

**Comment by davidmarkclements** [comment]
hey @benrei if you update the text to state it's an alternative to express-pino-logger and then explain the trade-offs I'd be happy to accept the PR

**Comment by jsumners** [comment]
Closing this as it seems abandoned. Please reopen if you find the time to address the feedback and take this over the finish line.

**Pull request closed without merging**
