### PR TITLE
Removed coveralls, removed TS badge

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by kibertoad** [comment]
Why remove coverage?

**Comment by mcollina** [comment]
1. Coveralls is continuosly down
2. We enforce 100% code coverage via tap

**Comment by kibertoad** [comment]
1. They were doing maintenance, it's almost done by now: https://status.coveralls.io/
2. Can we add some badge for that?

**Comment by mcollina** [comment]
@kibertoad they went down on the 18th and it's the 20th and they did not come back yet. I'm not sure we can depend on them.

We do not have a badge for it... I'd be happy for suggestions.

**Review by jsumners — APPROVED** [review]

**Pull request merged**
