### PR TITLE
Add MySQL/MariaDB transport

### PR DESCRIPTION
**Pull request by theproductiveprogrammer**
Hi - I've added a transport for MySQL/MariaDB which can extract fields from anywhere in the log stream and map them to database columns. It can also save the entire stream as a JSON field in MySQL. I found this useful for my latest project using the wonderful pino logger.
You can check the release here: https://www.npmjs.com/package/pino-mysql

### CODE REVIEW

**Comment by davidmarkclements** [comment]
once @jsumners feedback is addressed and resolved we're good to merge 👍

**Comment by theproductiveprogrammer** [comment]
> Wouldn't you at least want to suggest this schema?
> 
> ```sql
> create table logs (
>   id int(10) unsigned not null auto_increment primary key,
>   created timestamp default current_timestamp,
>   log json,
> 
>   index created (created)
> )
> ```
> 
> And _maybe_ an index on JSON? Maybe also show some generated columns to index specific values in JSON.

I've provided a couple of minimal DB schema's in the README and it also contains some examples of extracting fields from the log.

**Comment by jsumners** [comment]
There is no blockage from me on this PR. I'll just point out that you can save cycles in your transport by defining a column like:

```sql
req_url varchar generated always as ( json_unquote(json_extract(log, '$.req.url')) ) stored
```

Basically, let the database engine take care of extracting the field if it exists.

**Comment by theproductiveprogrammer** [comment]
@jsumners I didn't know MySQL could do that. Thanks! That's very cool. I've added your suggestion to the README as well.

**Pull request merged**
