### PR TITLE
Do not use SonicBoom for stdout on Lambda

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/pinojs/pino/issues/488

@thomasmichaelwallace can you please verify that this PR fixes the problem?

### CODE REVIEW

**Comment by davidmarkclements** [comment]
I'm not sure about this, perhaps we should instead have a pino-lamda module - that calls pino with process.stdout , and uses process.nextTick to flushSync at the end of the function

**Comment by mcollina** [comment]
You can’t pass in a serverless-specific config, because we overwrite the stream if it’s stdout. That’s part of what this PR fixes as well.

**Comment by davidmarkclements** [comment]
ah yes.. what about an option: `useNodeSTDIO`

**Comment by mcollina** [comment]
I would prefer if it worked by default on Lambda.
Il giorno gio 16 ago 2018 alle 16:31 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by jsumners** [comment]
I agree with @mcollina. Now that I do everything in AWS (Lambda, ECS, CloudWatch, all of that) there are things here that I think we need to be more lenient about to make the library useful in an increasingly popular environment / usage pattern (more on it later). The short of it is that someone using Pino in Lambda shouldn't have to think about it; it should just work.

Also, regarding the pipes, that's definitely an issue. It's definitely possible to freeze a process in a regular *nix environment -- http://web.mit.edu/gnu/doc/html/features_5.html

**Comment by davidmarkclements** [comment]
ok, fair enough - let's go with it

**Comment by davidmarkclements** [comment]
we still should think of a more graceful way around the flushSync situation

**Pull request merged**
