### PR TITLE
Pretty accepts custom logLevel

### PR DESCRIPTION
**Pull request by itavy**
fix for #172

### CODE REVIEW

**Comment by davidmarkclements** [comment]
should we do this? or should we allow flags to set the level num -> colors?

**Comment by jsumners** [comment]
@davidmarkclements it's not allowing customization of the colors, it's fixing no color assigned to custom levels causing a crash.

**Comment by itavy** [comment]
all other transports accept customLogLevel without any other configuration. pretty i see it as another transport and also it shal support anything that receives from pino;

i usually use pretty for local develop and pino-elasticsearch for production or beta testing; 

IMHO transports should be able to interchange without any other configuration

**Comment by davidmarkclements** [comment]
agreed.

**Comment by davidmarkclements** [comment]
v.3.1.2 published to npm and gh released - thanks @itavy !

**Pull request merged**
