### PR TITLE
fix: test for multiple caller entries

### PR DESCRIPTION
**Pull request by moshie**
Fixes: #1303

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by mcollina** [comment]
Does it fix your problem?

**Comment by moshie** [comment]
yes it does 👍

**Comment by moshie** [comment]
I was just looking at the documentation and noticed that the docs are specifying that caller is an option:
https://getpino.io/#/docs/api?id=pinotransportoptions-gt-threadstream

Here I have changed it to callers this may end up breaking some people's implementations.

I can update the docs and the implementation to accept caller and callers then wrap caller in an array?

**Comment by moshie** [comment]
@mcollina This should be ready for a review whenever you're ready 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
